max_threads: 8


# evaluate effect of parametr
pe_thread_step: [1, 9, 1] # begin, end (exclude), step
pe_quantity_step: [10, 55, 5] # begin, end (exclude), step
pe_identity_step: [85, 100, 1] # begin, end (exclude), step
